export const COMBAT_BOUNDS = { left: 24, right: 936, top: 64, bottom: 520 } as const;

export const BALANCE = {
  hero: {
    maxHealth: 100,
    speed: 190,
    attackDamage: [9, 11, 15] as readonly number[],
    attackRange: [62, 67, 78] as readonly number[],
    attackCooldown: 210,
    attackHitDelay: 86,
    attackRecovery: 190,
    comboStrikeInterval: 330,
    comboReset: 540,
    inputBuffer: 150,
    attackOriginOffset: 17,
    attackLungeMaximum: 28,
    attackLungeDuration: 64,
    secondaryTargetDamageMultiplier: 0.45,
    maximumSecondaryTargets: 2,
    eliteFrontalDamageMultiplier: 0.75,
    dashSpeed: 520,
    dashDuration: 170,
    dashCooldown: 760,
    dashInvulnerability: 220,
    hitInvulnerability: 620,
    parryWindow: 155,
    perfectParryWindow: 70,
    parryCooldown: 430,
    parryCounterBonus: 1.35,
    parryCounterWindow: 1500,
    parryVulnerability: 1600,
    parryHitstop: 90,
    parryPositionLock: 300,
    parryAttackerStagger: 300,
    parryAttackerCorrectionMaximum: 4,
    parryEnvelopePadding: 10,
    parryArc: 1.25,
    parryAssistRadius: 112,
    parryAssistMaxAngle: 0.82,
    defensiveSlash: {
      enabledByDefault: false,
      interval: 1000,
      range: 50,
      damage: 6,
      sentenceGain: 2,
      halfAngle: 0.9,
      knockback: 34,
    },
    finisher: {
      maximumCharges: 3,
      roundStartCharges: 1,
      damage: 34,
      range: 86,
      assistRange: 104,
      lungeMaximum: 18,
      hitDelay: 96,
      recovery: 270,
      cooldown: 310,
      halfAngle: 0.64,
      stoppedMultiplier: 1.25,
      stoppedBurstDamage: 16,
      stoppedBurstRadius: 82,
      linkedMultiplier: 1.08,
      linkedReactionRatio: 0.18,
      echoMultiplier: 1.2,
      echoDuration: 2200,
      echoReplayRatio: 0.34,
      knockback: 185,
      hitstop: 62,
    },
    basicAttack: {
      aimAssistHalfAngle: 0.44,
      holdRepeatDelay: 70,
      thirdHitSentenceGain: 6,
    },
    echoBlade: {
      interval: 950,
      range: 92,
      damage: 5,
      maximumTargets: 3,
      sentenceGain: 1.25,
    },
    cut: {
      damage: 14,
      range: 108,
      halfAngle: Math.PI * 5 / 12,
      cooldown: 1050,
      hitDelay: 115,
      recovery: 245,
      maximumTargets: 4,
      sentenceGain: 5,
      stoppedMultiplier: 1.65,
      stoppedBurstDamage: 13,
      stoppedBurstRadius: 76,
      linkedMultiplier: 1.2,
      linkedReactionDamage: 8,
      echoMultiplier: 1.35,
      echoReplayRatio: 0.45,
      exposedMultiplier: 1.5,
      knockback: 72,
      hitstop: 48,
    },
  },
  sentence: {
    maximum: 100,
    hitGain: 4,
    thirdHitGain: 6,
    parryGain: 18,
    perfectParryBonus: 12,
    wordHitGain: 6,
    chainGain: 12,
    killGain: 8,
    nearMissGain: 8,
  },
  words: {
    stopCooldown: 6000,
    rewindCooldown: 7500,
    linkCooldown: 9000,
    stopDamage: 10,
    rewindDamage: 16,
    rewindDamageRadius: 82,
    linkDamage: 6,
    singleLinkDamageMultiplier: 1.5,
    singleLinkDamageTakenMultiplier: 1.18,
    stopRadius: 145,
    stopDuration: 1300,
    rewindDuration: 2000,
    linkDuration: 5000,
    linkShare: 0.32,
    empoweredLinkShare: 0.42,
    stopFallbackDistance: 185,
    stopMaximumDistance: 270,
    linkSelectionRadius: 265,
    baseLinkTargets: 3,
    empoweredLinkTargets: 5,
  },
  targeting: {
    attackRange: 62,
    lungeRange: 28,
    wordRange: 270,
    emergencyDistance: 24,
    distanceTie: 6,
    forwardTieWeight: 9,
    threatTieWeight: 5,
    markerLerp: 0.32,
    markerDuration: 420,
  },
  chain: {
    window: 3800,
    perfectParryExtension: 600,
    linkStopDuration: 900,
    backflowDamageRatio: 0.72,
    damageHistoryDuration: 2000,
    damageHistoryRetention: 2300,
    damageRegressionRatio: 0.3,
    minimumBackflowDamage: 8,
    minimumRegressionDamage: 7,
    chainStopDamage: 7,
    empoweredFollowupSentence: 35,
    labelDuration: 850,
  },
  pacing: {
    waveSpawnInterval: 330,
    waveCompleteDelay: 150,
    rewardRevealDelay: 500,
    roundClearStability: 320,
    staleEnemyRecovery: 1500,
    bossDefeatDuration: 1800,
    miniWaveIntermission: 680,
    firstWaveAttackGrace: 2000,
    attackReservation: 720,
    firstWaveAttackStagger: 850,
    roundHealRatio: 0.18,
    firstRoundMinimumHealth: 60,
  },
  boss: {
    phaseTransition: 1100,
    phaseOpeningDelay: 420,
    entryMinimumHealth: 45,
    rewindVulnerability: 1600,
    vulnerabilityMultiplier: 1.28,
    reflectedPhaseOneMultiplier: 1.4,
    separationRadius: 92,
    vulnerabilityDuration: 1750,
    phaseSentenceMinimum: 35,
  },
  collision: {
    heroMovementRadius: 15,
    heroHurtRadiusX: 13,
    heroHurtRadiusY: 20,
    heroHurtOffsetY: -20,
    projectileRadius: 5,
    daggerHalfAngle: 0.72,
    meleeTelegraphPadding: 1.08,
    enemySeparationStrength: 0.26,
    heroSeparationStrength: 0.58,
    heroSeparationShare: 0.38,
    bossHeroSeparationShare: 0.88,
    maximumSeparationStep: 2.5,
    separationIterations: 2,
    movementRadius: { chaser: 18, archer: 18, ink: 20, elite: 27, boss: 44, minion: 17 },
    hurtRadiusX: { chaser: 16, archer: 15, ink: 18, elite: 24, boss: 34, minion: 15 },
    hurtRadiusY: { chaser: 23, archer: 22, ink: 22, elite: 32, boss: 45, minion: 21 },
    hurtOffsetY: { chaser: -20, archer: -19, ink: -22, elite: -27, boss: -38, minion: -18 },
    visualHalfWidth: { chaser: 26, archer: 27, ink: 27, elite: 43, boss: 60, minion: 26 },
    visualHeight: { chaser: 60, archer: 60, ink: 62, elite: 91, boss: 132, minion: 60 },
  },
  enemies: {
    chaser: { hp: 64, speed: 94, damage: 15, score: 120 },
    archer: { hp: 50, speed: 72, damage: 13, score: 160 },
    ink: { hp: 42, speed: 48, damage: 11, score: 180 },
    elite: { hp: 210, speed: 58, damage: 22, score: 600 },
    boss: { hp: 900, speed: 68, damage: 24, score: 3000 },
  },
  enemyAI: {
    pursuitResumeDistance: { chaser: 64, archer: 292, ink: 272, elite: 82, boss: Number.POSITIVE_INFINITY, minion: 64 },
    pursuitRecoverySpeedRatio: 0.72,
  },
  waveSpawns: [
    [['chaser', 'chaser'], ['chaser', 'archer']],
    [['archer', 'ink'], ['archer', 'ink', 'chaser']],
    [['elite', 'chaser'], ['archer', 'ink', 'chaser']],
  ] as const,
} as const;

export type EnemyKind = 'chaser' | 'archer' | 'ink' | 'elite' | 'boss' | 'minion';

export function enemyGroundExtents(kind: EnemyKind): Readonly<{ left: number; right: number; top: number; bottom: number }> {
  const movement = BALANCE.collision.movementRadius[kind];
  const hurtX = BALANCE.collision.hurtRadiusX[kind];
  const hurtY = BALANCE.collision.hurtRadiusY[kind];
  const hurtOffsetY = BALANCE.collision.hurtOffsetY[kind];
  const horizontal = Math.max(movement, hurtX, BALANCE.collision.visualHalfWidth[kind]);
  return {
    left: horizontal,
    right: horizontal,
    top: Math.max(movement, -hurtOffsetY + hurtY, BALANCE.collision.visualHeight[kind]),
    bottom: Math.max(movement, hurtOffsetY + hurtY),
  };
}
