export const BALANCE = {
  hero: {
    maxHealth: 100,
    speed: 190,
    attackDamage: [18, 22, 34] as readonly number[],
    attackRange: [62, 67, 78] as readonly number[],
    attackCooldown: 210,
    attackHitDelay: 62,
    attackRecovery: 128,
    comboReset: 540,
    inputBuffer: 150,
    dashSpeed: 520,
    dashDuration: 170,
    dashCooldown: 760,
    dashInvulnerability: 220,
    hitInvulnerability: 620,
    parryWindow: 155,
    perfectParryWindow: 70,
    parryCooldown: 430,
    parryCounterBonus: 1.35,
    parryCounterWindow: 1500,
    parryVulnerability: 1600,
    parryHitstop: 90,
    parryArc: 1.25,
    parryAssistRadius: 112,
    parryAssistMaxAngle: 0.82,
  },
  sentence: {
    maximum: 100,
    hitGain: 6,
    parryGain: 28,
    nearMissGain: 8,
    stopCost: 25,
    rewindCost: 30,
    linkCost: 35,
  },
  words: {
    stopRadius: 145,
    stopDuration: 1300,
    rewindDuration: 2000,
    linkDuration: 5000,
    linkShare: 0.28,
    empoweredLinkShare: 0.42,
    stopFallbackDistance: 185,
    stopMaximumDistance: 270,
    linkSelectionRadius: 265,
  },
  targeting: {
    maximumRange: 390,
    retainRange: 430,
    forwardDot: 0.37,
    markerLerp: 0.22,
    minimumHold: 420,
    switchThreshold: 0.18,
    distanceWeight: 0.44,
    angleWeight: 0.36,
    currentBonus: 0.3,
    threatWeight: 0.2,
    priorityWeight: 0.16,
    closeDangerWeight: 0.18,
    closeDangerDistance: 96,
  },
  chain: {
    window: 2500,
    secondWordCostDiscount: 0.25,
    perfectParryExtension: 600,
    linkStopDuration: 900,
    backflowDamageRatio: 0.72,
    damageHistoryDuration: 2000,
    damageHistoryRetention: 2300,
    damageRegressionRatio: 0.3,
    empoweredFollowupSentence: 35,
    labelDuration: 850,
  },
  pacing: {
    waveSpawnInterval: 330,
    waveCompleteDelay: 150,
  },
  boss: {
    phaseTransition: 1100,
    phaseOpeningDelay: 420,
    entryMinimumHealth: 45,
    rewindVulnerability: 1600,
    vulnerabilityMultiplier: 1.28,
    reflectedPhaseOneMultiplier: 1.4,
    separationRadius: 92,
    vulnerabilityDuration: 1750,
    phaseSentenceMinimum: 35,
  },
  collision: {
    heroMovementRadius: 15,
    heroHurtRadius: 16,
    heroHurtOffsetY: -14,
    projectileRadius: 5,
    daggerHalfAngle: 0.72,
    enemySeparationStrength: 0.26,
    heroSeparationStrength: 0.58,
    movementRadius: { chaser: 18, archer: 18, ink: 20, elite: 27, boss: 44, minion: 17 },
    hurtRadius: { chaser: 18, archer: 18, ink: 19, elite: 26, boss: 35, minion: 17 },
  },
  enemies: {
    chaser: { hp: 64, speed: 94, damage: 15, score: 120 },
    archer: { hp: 50, speed: 72, damage: 13, score: 160 },
    ink: { hp: 42, speed: 48, damage: 11, score: 180 },
    elite: { hp: 210, speed: 58, damage: 22, score: 600 },
    boss: { hp: 900, speed: 68, damage: 24, score: 3000 },
  },
  waveSpawns: [
    ['chaser', 'chaser', 'chaser', 'archer'],
    ['archer', 'ink', 'archer', 'ink', 'chaser'],
    ['elite', 'archer', 'ink', 'chaser'],
  ] as const,
} as const;

export type EnemyKind = 'chaser' | 'archer' | 'ink' | 'elite' | 'boss' | 'minion';
